[NH_COMMON]
NH_TCPIP = Enabled

[NH_TCPIP]
; Статический IP-адрес выделенного HASP License Manager
NH_SERVER_ADDR = 192.168.1.50
NH_PORT_NUMBER = 475
NH_TCPIP_METHOD = UDP
; Отключение широковещательного broadcast-поиска для предотвращения сетевых таймаутов
NH_USE_BROADCAST = Disabled
